---
- name: Setup
  hosts: localhost
  connection: local

  vars:
    work_mode: false
    supported_distributions:
      - ubuntu
      - archlinux

  pre_tasks:
    - name: Check for supported distribution
      ansible.builtin.fail:
        msg: "Distribution {{ ansible_distribution }} is not supported"
      when: ansible_distribution | lower not in supported_distributions

    - name: Personal mode
      ansible.builtin.debug:
        msg: "Running in personal mode"
      when: not work_mode | bool

    - name: Work mode
      ansible.builtin.debug:
        msg: "Running in work mode"
      when: work_mode | bool

    - name: Include variables
      include_vars: "modules/private/vault.yml"
      when: not work_mode | bool

  tasks:
    - name: Setup dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: Setup SSH
      include_tasks: tasks/ssh.yml

    - name: Setup GPG and Git
      include_tasks: tasks/git.yml

    - name: Setup personal
      include_tasks: tasks/personal.yml
      when: not work_mode | bool

    - name: Setup misc
      include_tasks: tasks/misc.yml
