---
- name: Setup
  hosts: localhost
  connection: local

  vars_files:
    - modules/private/vault.yml

  vars:
    work_mode: false

  pre_tasks:
    - name: Check for supported distribution
      ansible.builtin.fail:
        msg: "Distribution {{ ansible_distribution }} is not supported"
      when: ansible_distribution | lower not in ['macosx', 'ubuntu']

    - name: Personal mode
      ansible.builtin.debug:
        msg: "Running in personal mode"
      when: not work_mode | bool

    - name: Work mode
      ansible.builtin.debug:
        msg: "Running in work mode"
      when: work_mode | bool

    - name: Setup dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: Setup personal
      include_tasks: tasks/personal.yml
      when: not work_mode | bool

    - name: Setup SSH (personal)
      include_tasks: tasks/ssh_personal.yml
      when: not work_mode | bool

    - name: Setup GPG and Git (personal)
      include_tasks: tasks/git_personal.yml
      when: not work_mode | bool

    - name: Setup misc
      include_tasks: tasks/misc.yml
