---
- name: Install Packages
  hosts: localhost
  connection: local
  vars_files:
    - vars/packages.yml

  pre_tasks:
    - name: Check for supported distribution
      ansible.builtin.fail:
        msg: "Distribution {{ ansible_distribution }} is not supported"
      when: ansible_distribution | lower not in ['macosx', 'ubuntu']

    - name: Update package cache (Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution | lower == 'ubuntu'
      become: true

  tasks:
    - name: Install tools & applications
      include_tasks: tasks/install_package.yml
      vars:
        package: "{{ item }}"
      loop: "{{ flattened_packages }}"
      loop_control:
        label: "Installing {{ item.name }}"
      when: item[ansible_distribution | lower] is defined

    - name: Setup dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: Setup SSH
      include_tasks: tasks/ssh.yml

    - name: Setup GPG and Git
      include_tasks: tasks/git_config.yml

    - name: Configure macOS settings
      include_tasks: tasks/macos_settings.yml
      when: ansible_distribution | lower == 'macosx'

    - name: Setup misc
      include_tasks: tasks/misc.yml
