---
- name: Setup dotfiles
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Check for supported distribution
      ansible.builtin.fail:
        msg: "Distribution {{ ansible_distribution }} is not supported"
      when: ansible_distribution | lower not in ['macosx', 'ubuntu']

    - name: Setup dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: Setup SSH
      include_tasks: tasks/ssh.yml

    - name: Setup GPG and Git
      include_tasks: tasks/git_config.yml

    # - name: Configure macOS settings
    #   include_tasks: tasks/macos_settings.yml
    #   when: ansible_distribution | lower == 'macosx'

    - name: Setup misc
      include_tasks: tasks/misc.yml
