---
- name: Include variables
  include_vars: "modules/private/vault.yml"

- name: Ensure .gnupg directory exists
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    mode: "0700"

- name: Set proper permissions for .gnupg subdirectories
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    mode: "0700"
    recurse: yes
  when: (ansible_env.HOME + '/.gnupg') is directory

- name: Find GPG binary
  command: which gpg
  register: gpg_path
  changed_when: false
  failed_when: gpg_path.rc != 0

- name: Set GPG program path fact
  set_fact:
    default_gpg_program: "{{ gpg_path.stdout }}"

- name: Import GPG private keys
  shell: echo "{{ item.private_key }}" | "{{ default_gpg_program }}" --batch --import
  loop: "{{ gpg.credentials }}"
  no_log: true
  changed_when: false

- name: Import GPG public keys
  shell: echo "{{ item.public_key }}" | "{{ default_gpg_program }}" --batch --import
  loop: "{{ gpg.credentials }}"
  no_log: true
  changed_when: false

- name: Configure .gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: "0644"
  vars:
    git_user_name: "Marius Jørgensen"
    git_user_email: "{{ git.email }}"
    git_signing_key: "{{ git.gpg_key_id }}"
    git_gpg_program: "{{ default_gpg_program }}"
