---
# Find some settings with defaults read -g
# Figure out how to make these work (works when run manually, but not via osx_defaults):
# defaults write -g com.apple.swipescrolldirection -boolean YES
# Others: Disable all Spotlight settings
- name: Configure macOS settings
  when: ansible_distribution | lower == 'macosx'
  block:
    - name: Enable Dock auto-hide
      osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true

    - name: Disable showing recent apps in Dock
      osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false

    - name: Enable Dock magnification
      osx_defaults:
        domain: com.apple.dock
        key: magnification
        type: bool
        value: true

    - name: Set Dock tile size
      osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: int
        value: 32

    - name: Set Dock large size
      osx_defaults:
        domain: com.apple.dock
        key: largesize
        type: int
        value: 48

    - name: Set persistent apps in Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: persistent-apps
        type: array
        value: "{{ dock_template }}"
      vars:
        macos_dock_apps:
          - "/Applications/Brave Browser.app"
          - "/Applications/Ghostty.app"
          - "/Applications/Obsidian.app"
          - "/System/Applications/Mail.app"
          - "/System/Applications/Calendar.app"
        value_start: "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>"
        value_end: "</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
        dock_template: |
          [{% for app in macos_dock_apps %}
            "{{ value_start }}{{ app }}{{ value_end }}"{{ "," if not loop.last else "" }}
          {% endfor %}]

    # Remove Spotlight icon from menu bar
    - name: Remove Spotlight from menu bar
      osx_defaults:
        domain: com.apple.Spotlight
        key: MenuItemHidden
        type: bool
        value: true

    # Hide input menu in menu bar
    - name: Hide input menu in menu bar
      osx_defaults:
        domain: com.apple.TextInputMenu
        key: visible
        type: bool
        value: false

    # Finder settings
    - name: Show all files in Finder
      osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllFiles
        type: bool
        value: true

    - name: Show all extensions in Finder
      osx_defaults:
        domain: com.apple.finder
        key: AppleShowAllExtensions
        type: bool
        value: true

    - name: Set preferred view style for Finder
      osx_defaults:
        domain: com.apple.finder
        key: FXPreferredViewStyle
        type: string
        value: "clmv"

    # Global domain settings
    - name: Show all files globally
      osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllFiles
        type: bool
        value: true

    - name: Show all extensions globally
      osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true

    - name: Use 24-hour time
      osx_defaults:
        domain: NSGlobalDomain
        key: AppleICUForce24HourTime
        type: bool
        value: true

    - name: Set dark mode
      osx_defaults:
        domain: NSGlobalDomain
        key: AppleInterfaceStyle
        type: string
        value: "Dark"

    - name: Disable natural scrolling
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: false

    # Login window settings
    - name: Disable guest login
      osx_defaults:
        domain: com.apple.loginwindow
        key: GuestEnabled
        type: bool
        value: false

    # Menu extra clock settings
    - name: Show seconds in menu bar clock
      osx_defaults:
        domain: com.apple.menuextra.clock
        key: ShowSeconds
        type: bool
        value: true

    - name: Show day of week in menu bar clock
      osx_defaults:
        domain: com.apple.menuextra.clock
        key: ShowDayOfWeek
        type: bool
        value: true

    - name: Show date in menu bar clock
      osx_defaults:
        domain: com.apple.menuextra.clock
        key: ShowDate
        type: int
        value: 1

    # Screenshot settings
    - name: Set screenshot location
      osx_defaults:
        domain: com.apple.screencapture
        key: location
        type: string
        value: "~/Desktop/Screenshots"

    # Create screenshot directory if it doesn't exist
    - name: Ensure screenshot directory exists
      file:
        path: "{{ ansible_env.HOME }}/Desktop/Screenshots"
        state: directory
        mode: "0755"

    # Restart affected services to apply changes
    - name: Restart Dock to apply changes
      command: killall Dock
      ignore_errors: true

    - name: Restart Finder to apply changes
      command: killall Finder
      ignore_errors: true

    - name: Restart SystemUIServer to apply menu bar changes
      command: killall SystemUIServer
      ignore_errors: true
# TODO: Look into the below

# - name: Set default browser to Brave
#   shell: defaultbrowser brave
#   ignore_errors: true
#   register: browser_result
#   failed_when: browser_result.rc != 0 and "defaultbrowser not found" not in browser_result.stderr

# - name: Configure Finder favorites sidebar
#   osx_defaults:
#     domain: com.apple.sidebarlists
#     key: favoriteditems
#     type: array
#     value: "{{ finder_favorites }}"
#   vars:
#     finder_locations:
#       - name: "Home"
#         path: "{{ ansible_env.HOME }}"
#       - name: "Desktop"
#         path: "{{ ansible_env.HOME }}/Development"
#       - name: "Desktop"
#         path: "{{ ansible_env.HOME }}/Desktop"
#       - name: "Documents"
#         path: "{{ ansible_env.HOME }}/Documents"
#       - name: "Downloads"
#         path: "{{ ansible_env.HOME }}/Downloads"
#       - name: "Applications"
#         path: "/Applications"
#     finder_favorites: |
#       [
#       {% for item in finder_locations %}
#         {
#           'name': '{{ item.name }}',
#           'url': 'file://{{ item.path }}'
#         }{{ "," if not loop.last else "" }}
#       {% endfor %}
#       ]

# Enable desktop icon snap to grid
# - name: Enable icon snap to grid on desktop
#   osx_defaults:
#     domain: com.apple.finder
#     key: DesktopViewOptions
#     type: dict
#     value:
#       IconViewSettings:
#         arrangeBy: grid
#         gridSpacing: 100
#         iconSize: 64
#         labelOnBottom: true
#         showIconPreview: true
#         showItemInfo: false
#         textSize: 12

# Configure Night Shift to use Sunset to Sunrise
# - name: Enable Night Shift from Sunset to Sunrise
#   osx_defaults:
#     domain: com.apple.CoreBrightness
#     key: CBBlueReductionStatus
#     type: dict
#     value:
#       AutoBlueReductionEnabled: 1
#       BlueLightReductionSchedule:
#         CurrentTime: null
#         StartTime: -1 # -1 means sunset
#         EndTime: -1 # -1 means sunrise
