---
- name: Clone notes repository
  ansible.builtin.git:
    repo: https://github.com/marjorg/notes
    dest: "{{ ansible_env.HOME }}/notes"
    clone: yes
    update: no

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    clone: yes
    update: no

# TODO: Figure out how to check changed below
- name: Install Node.js LTS version with NVM
  shell: |
    export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
    source $NVM_DIR/nvm.sh
    nvm install --lts
  args:
    executable: /bin/bash

- name: Set default Node.js version
  shell: |
    export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
    source $NVM_DIR/nvm.sh
    nvm alias default node
  args:
    executable: /bin/bash

- name: Enable pnpm with corepack
  shell: corepack enable pnpm
  args:
    executable: /bin/bash

- name: Install global npm packages
  shell: npm install -g clinic eas-cli turbo
  args:
    executable: /bin/bash
