---
- name: Clone notes repository
  ansible.builtin.git:
    repo: git@github.com:marjorg/notes.git
    dest: "{{ ansible_env.HOME }}/notes"
    clone: yes
    update: no

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    clone: yes
    update: no
