---
- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    clone: yes
    update: no

- name: Create .zshenv with environment variables
  template:
    src: "templates/zshenv.j2"
    dest: "{{ ansible_env.HOME }}/.zshenv"
    mode: "0600"
  no_log: true
