---
- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: Create private SSH keys
  copy:
    content: "{{ item.private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}"
    mode: "0600"
  loop: "{{ ssh.credentials }}"
  when: ssh is defined
  no_log: true

- name: Create public SSH keys
  copy:
    content: "{{ item.public_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}.pub"
    mode: "0644"
  loop: "{{ ssh.credentials }}"
  when: ssh is defined
  no_log: true

- name: Check if a key already exists
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
  register: ssh_stat

- name: Generate SSH key with script if not present
  script: ./scripts/generate-ssh-key.sh {{ email }}
  args:
    creates: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
  when: not ssh_stat.stat.exists

- name: Ensure github.com is in known_hosts
  when: not work_mode | bool
  known_hosts:
    path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
    state: present
