---
- name: Include variables
  include_vars: "modules/private/vault.yml"

- name: Ensure .ssh directory exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: Create private SSH keys
  copy:
    content: "{{ item.private_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}"
    mode: "0600"
  loop: "{{ ssh.credentials }}"
  no_log: false

- name: Create public SSH keys
  copy:
    content: "{{ item.public_key }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}.pub"
    mode: "0644"
  loop: "{{ ssh.credentials }}"
  no_log: true

- name: Create SSH config file
  template:
    src: "templates/ssh_config.j2"
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: "0644"

- name: Ensure github.com is in known_hosts
  known_hosts:
    path: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
    state: present
