---
# Get paths of all package files
package_files: "{{ lookup('ansible.builtin.fileglob', playbook_dir + '/vars/packages/*.yml', wantlist=True) }}"

# Create a dictionary mapping each category name to its file content
package_categories: >-
  {%- set categories = {} -%}
  {%- for file_path in package_files -%}
    {%- set filename = file_path.split('/')[-1].split('.')[0] -%}
    {%- set file_content = lookup('ansible.builtin.file', file_path) | from_yaml -%}
    {%- if file_content[filename] is defined -%}
      {%- set _ = categories.update({filename: file_content[filename]}) -%}
    {%- endif -%}
  {%- endfor -%}
  {{ categories }}

# Create flattened list with all packages
flattened_packages: >-
  {%- set all_packages = [] -%}
  {%- for category_name, packages in (package_categories | from_yaml).items() -%}
    {%- set _ = all_packages.extend(packages) -%}
  {%- endfor -%}
  {{ all_packages }}
