# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

bindd = SUPER, RETURN, Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"

bindd = SUPER SHIFT, S, Screenshot to clipboard, exec, omarchy-cmd-screenshot smart clipboard
