[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 4
opacity = 0.8
blur = true

[font]
bold.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
normal.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
size = 12.0
